#ifndef __SAMPLE_SETTING_H_
#define __SAMPLE_SETTING_H_

//TODO: to set
#define ONE_INTERVAL_TOTAL_VOLUME 100000000

#define OVER_SAMPLING_RATIO 4
#define DEFAULT_BYTE_SAMPLE_RATE (1.0 / TARGET_FLOW_VOLUME * OVER_SAMPLING_RATIO)
#define SH_HASHMAP_SIZE (DEFAULT_BYTE_SAMPLE_RATE * ONE_INTERVAL_TOTAL_VOLUME)

#endif
